# Generated by Django 4.1.7 on 2023-03-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_puoduct_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OderTtem',
            new_name='OrderTtem',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dete_oder',
            new_name='dete_order',
        ),
        migrations.RenameField(
            model_name='orderttem',
            old_name='oder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='oder',
            new_name='order',
        ),
    ]
